id: P004140
initial_creation_type: ocr
source_metadata:
  id: bdr:W1EE19
  title: ཤེར་ཕྱིན་བརྒྱད་སྟོང་པ།（སོག་ཡིག）
  author: ''
  volumes:
    c00f0ddb69654b6289e95b9ccad39e97:
      image_group_id: I1KG16974
      title: ''
      volume_number: 1
      total_pages: 836
      base_file: v001.txt
